resolver: lts-14.23
packages:

- smos
- smos-data
- smos-data-gen
- smos-cursor
- smos-cursor-gen
- smos-report
- smos-report-gen
- smos-report-cursor
- smos-report-cursor-gen
- smos-query
- smos-single
- smos-scheduler
- smos-convert-org
- smos-archive
- smos-docs-site
- smos-api
- smos-api-gen
- smos-server
- smos-server-gen
- smos-client
- smos-client-gen
- smos-sync-client
- smos-sync-client-gen
- smos-web-server


  # - /home/syd/src/mergeful/mergeful
  # - /home/syd/src/mergeful/mergeful-persistent
  # - /home/syd/src/mergeful/genvalidity-mergeful
extra-deps:
- envparse-0.4.1@sha256:989902e6368532548f61de1fa245ad2b39176cddd8743b20071af519a709ce30,2842
- servant-flatten-0.2@sha256:276896f7c5cdec5b8f8493f6205fded0cc602d050b58fdb09a6d7c85c3bb0837,1234

- base64-0.4.2@sha256:e9523e18bdadc3cab9dc32dfe3ac09c718fe792076326d6d353437b8b255cb5b,2888
- ghc-byteorder-4.11.0.0.10@sha256:5ee4a907279bfec27b0f9de7b8fba4cecfd34395a0235a7784494de70ad4e98f,1535
- github: cdepillabout/password 
  commit: 26434d4f6888faf8dc36425b20b59f0b5056d7f5
  subdirs:
    - password
    - password-instances


- github: haskell-servant/servant-auth
  commit: 62d3f4b6a7fd7dc38510d4c60982239f94fc1b58
  subdirs:
    - servant-auth-client
    - servant-auth-docs
    - servant-auth-swagger
    - servant-auth-server


- github: NorfairKing/typed-uuid
  commit: 5415eaeee9817dfc4846fe4d73efce9312281b27
  subdirs:
  - typed-uuid
  - genvalidity-typed-uuid

# https://github.com/vincenthz/hs-tls/issues/421
# see also nix/overlay.nix.
- github: ocheron/hs-tls
  commit: f785ce66559a09d998bcb5d459cc5ec9d53d54f0
  subdirs:
    - core
    - debug
    - session

- github: GaloisInc/sqlite
  commit: e93ee84000c1d1eedbc23036c4a20ffd07e3145f

- github: NorfairKing/persistent
  commit: 0e3bbb1bd2f5f6383f9eb0407a2416e8b12255ee
  subdirs:
    - persistent
    - persistent-template
    - persistent-sqlite

- github: NorfairKing/mergeful
  commit: c1e4c5d65a0e7a4eb82d3680e77867a421ea8c29
  subdirs:
    - mergeful
    - mergeful-persistent
    - genvalidity-mergeful
- github: ixmatus/orgmode-parse
  commit: 1bdfbfe8fb7299724a6f6a122a93b2e96dd839f8
- github: NorfairKing/pretty-relative-time
  commit: fc62907b36f6f7348d6ae0e97aceb4d41039d57b
- github: NorfairKing/cursor-fuzzy-time
  commit: 0b1d393a64b0fd357a9ead86c1ef0d6bd2a4c19f
  subdirs:
    - cursor-fuzzy-time
    - cursor-fuzzy-time-gen
- github: NorfairKing/fuzzy-time
  commit: 0c32a1d2e09f1b7421918a845f0b57eceb6752a8
  subdirs:
    - fuzzy-time
    - fuzzy-time-gen

- github: NorfairKing/dirforest
  commit: c0657315e01683558a8f20b991bc47d4733ed40e
  subdirs:
    - dirforest
    - genvalidity-dirforest

- github: NorfairKing/cursor-dirforest
  commit: 383ebdf881a47b5a505e377cdf78de8f848a71c4
  subdirs:
    - cursor-dirforest
    - cursor-dirforest-gen
    - cursor-dirforest-brick

- github: NorfairKing/cursor-brick
  commit: 58b2c811c721885eaa3c066b41bc4d4883e4566c
  subdirs:
    - cursor-brick

- github: NorfairKing/cursor
  commit: ea6724d2a0127614e9062a5ea53de8f042506dd0
  subdirs:
    - cursor
    - cursor-gen

- github: NorfairKing/validity
  commit: b8c4cb4cafef7eb2feabaf767eb0d96c5fb5b573
  subdirs:
  - genvalidity
  - genvalidity-aeson
  - genvalidity-bytestring
  - genvalidity-containers
  - genvalidity-criterion
  - genvalidity-hspec
  - genvalidity-hspec-aeson
  - genvalidity-hspec-binary
  - genvalidity-hspec-cereal
  - genvalidity-hspec-hashable
  - genvalidity-hspec-optics
  - genvalidity-hspec-persistent
  - genvalidity-path
  - genvalidity-persistent
  - genvalidity-property
  - genvalidity-scientific
  - genvalidity-text
  - genvalidity-time
  - genvalidity-unordered-containers
  - genvalidity-uuid
  - genvalidity-vector
  - validity
  - validity-aeson
  - validity-bytestring
  - validity-containers
  - validity-path
  - validity-persistent
  - validity-primitive
  - validity-scientific
  - validity-text
  - validity-time
  - validity-unordered-containers
  - validity-uuid
  - validity-vector

- github: NorfairKing/yamlparse-applicative
  commit: ba2544632a21d0cfa0e2590f9a6a96fbbd026640
  subdirs:
  - yamlparse-applicative
nix:
  path: [ "nixpkgs=https://github.com/NixOS/nixpkgs/archive/323fe92057bb38475a446ff5e18d3b388c2e4403.tar.gz" ]
  add-gc-roots: true
  packages:
  - zlib
  - haskellPackages.autoexporter
  - killall
